- setup.py
@M-R-Sullivan can you please PR?
> Pull request for #43: Dependency on package "requests"

- README.md
- gslab_scons/_exception_classes.py
- gslab_scons/builders/build_lyx.py
- gslab_scons/builders/build_matlab.py
- gslab_scons/builders/build_python.py
- gslab_scons/builders/build_r.py
- gslab_scons/builders/build_stata.py
- gslab_scons/log.py
- gslab_scons/misc.py
- gslab_scons/tests/test_build_lyx.py
- gslab_scons/tests/test_build_python.py
- gslab_scons/tests/test_build_stata.py
- setup.py
What I did in this PR:
- add master to pip install git+ssh://git@github.com/gslab-econ/gslab_python.git and other instructions 
- The R builder is failing in Windows. Command line argument issue. Check if this hold true for others.
- Add setuptools as a requirement, and suggests pip as an installation tool.
- kinder time-log failure
> Pull request for #58: Prepare for 4.0

- gslab_scons/builders/build_python.py
- gslab_scons/log.py
@stanfordquan, can you please review my work from #75? Let me know if you'd like the error message to be printed in another manner. I went with what I thought would be most useful for me, but I don't have strong opinions.
> Pull request for #75: Print traceback for python builder

- gslab_fill/tablefill.py
- gslab_fill/tablefill_info.py
- gslab_fill/tests/test_tablefill.py
- gslab_scons/builders/build_tables.py
- gslab_scons/misc.py
- gslab_scons/tests/test_build_lyx.py
- gslab_scons/tests/test_build_tables.py
- test.log
@stanfordquan,
This should be a pretty short PR, so I think we can slot it into 4.0 release.
> Pull request for #73: Allows tablefill to use tex documents

- README.md
@lboxell, can you PR my work from #83?
> Pull request for #83: Add coverage to dependencies

- README.md
- gslab_scons/misc.py
- gslab_scons/size_warning.py
- gslab_scons/tests/test_size_warning.py
- setup.py
- test.log
@stanfordquan, I implemented fixes to the two issues. I can't remember whether we want to merge bug fixes directly to master or not. In this case, it seems like we'd want to (and raise to 4.0.1), but I'm open to other options. I attached what the state of repo looks like on a repo with no git history, which I think is good enough for our purposes, but let me know if you think otherwise. 
[state_of_repo.txt](https://github.com/gslab-econ/gslab_python/files/1192126/state_of_repo.txt)
> Pull request for #89: Fixes issues on new repo

- gslab_scons/builders/build_r.py
@stanfordquan , not sure what's our protocol on PR for this sprint. I have tested the updated `build_r` on `ad-price-drivers` but feel free to test this more or give any suggestions.
> Pull request for #98: R command line syntax

- gslab_scons/README.md
- gslab_scons/configuration_tests.py
- gslab_scons/misc.py
- gslab_scons/release.py
@yuchuan2016 , This is auxiliary for template gslab-econ/template#61. Should be quick.
> Pull request: Switch user_config.yaml to config_user.yaml

- gslab_scons/_exception_classes.py
- gslab_scons/builders/build_latex.py
- gslab_scons/builders/build_lyx.py
- gslab_scons/builders/build_matlab.py
- gslab_scons/builders/build_python.py
- gslab_scons/builders/build_r.py
- gslab_scons/builders/build_stata.py
- gslab_scons/builders/build_tables.py
- gslab_scons/misc.py
@yuchuan2016 , please see #95. I have test this a bit on template but please test it more and try to break it if you can. Thanks!
> Pull request for #95: Check target files after each building step

- gslab_scons/builders/build_r.py
- gslab_scons/builders/build_tables.py
- gslab_scons/tests/_side_effects.py
- gslab_scons/tests/_test_helpers.py
- gslab_scons/tests/config_user.yaml
- gslab_scons/tests/test_build_matlab.py
- gslab_scons/tests/test_build_python.py
- gslab_scons/tests/test_build_r.py
- gslab_scons/tests/test_build_stata.py
- gslab_scons/tests/test_log.py
- gslab_scons/tests/user-config.yaml
- test.log
I have fixed the unit tests failure. I have modified the test scripts for `build_r`, `build_stata`, `log` and `configuration_tests`. It would be great if @stanfordquan can take a loot at the stata and config tests, and @Shun-Yang can take a look at the r and log tests, as well as run these tests to see if they work. Thanks!
> Pull Request for #108: Fix unit tests in the current builders

- gslab_scons/README.md
- gslab_scons/_release_tools.py
- gslab_scons/release.py
@yuchuan2016 , this should be straightforward!
> Pull request for #111: Fix release.py

- .gitignore
- gslab_fill/tablefill.py
- gslab_fill/tests/input/tablefill_template.tex
- gslab_fill/tests/input/tablefill_template_breaks.tex
- gslab_fill/tests/input/tablefill_template_filled.tex
- gslab_fill/tests/test_tablefill.py
- test.log
@stanfordquan,
The tablefill function wasn't working as intended for latex. I made some changes to get it to work for my purposes. Feel free to take and integrate as you see fit (You'll want to edit the code if you use it; it was just a first pass to get things working for what I was doing). Let me know if you have any questions.
> Pull request: Bug in tablefill for latex

- gslab_scons/misc.py
@yuchuan2016 , this branches from `issue91_largewarnings` and is parallel to gslab-econ/template#81.
> Pull request for documenting and organizing debrief

- gslab_scons/README.md
- gslab_scons/_release_tools.py
- gslab_scons/provenance.py
- gslab_scons/release.py
@stanfordquan, can you please PR my work from #126. Let me know if you have any questions!
> Pull request for #126: Fix lingering issues with release.py

- gslab_scons/log.py
I did a check for where we may have hard-coded template directory structure into gslab_python. 
I listed those points [in this comments](https://github.com/gslab-econ/gslab_python/issues/130#issuecomment-328647545). 
In peer review, please check that the list is correct and complete, and that you agree with my decisions / fixes. Thanks!
> Pull request for #130: Uncouple directory structure from gslab_python

- gslab_scons/record_dir.py
- setup.py
@stanfordquan, can you review my work from #136? It's all of four lines of code, so it'd be great to knock out quickly.
> Pull request for #136: Single file state of inputs

- gslab_scons/builders/build_matlab.py
@Shun-Yang, can you PR my work from #142. Make sure you can get a complete run of template/analysis using the new matlab builder. Thanks!
> Pull request for #142: Allow parallelization in MATLAB builder

- gslab_scons/builders/build_anything.py
- gslab_scons/builders/build_latex.py
- gslab_scons/builders/build_lyx.py
- gslab_scons/builders/build_matlab.py
- gslab_scons/builders/build_python.py
- gslab_scons/builders/build_r.py
- gslab_scons/builders/build_stata.py
- gslab_scons/builders/build_tables.py
- gslab_scons/builders/gslab_builder.py
@arosenbe , as discussed, I added `os.path.normpath` to when paths are called in builders. Thanks! 👩‍🎨
> Pull request for #147: Add os.path.normpath to log and source path calls

- gslab_scons/log.py
Hi @z-y-huang , I made a simple change removing an unused argument in start_log. Issue at #159 .
> Pull Request for 159: Remove unused argument in start_log

- gslab_scons/check_prereq.py
- gslab_scons/log.py
- gslab_scons/misc.py
Hi @mengsongouyang. Can you PR the new version of gslab_python? This addresses bugs raised in #159, #161, and #162.
> Pull Request for 4.1.3: #159, #161, and #162

- gslab_scons/log_paths_dict.py
- setup.py
@mollywharton @mengsongouyang. I made a small change to the python dependencies. Can you confirm that what I did makes sense and that you're able to install the package on your machines?
> Pull Request for #167: Remove mmh3 dependency

- gslab_scons/__init__.py
- gslab_scons/builders/build_mathematica.py
- gslab_scons/check_prereq.py
- gslab_scons/misc.py
- gslab_scons/tests/_side_effects.py
- gslab_scons/tests/_test_helpers.py
- gslab_scons/tests/test_build_mathematica.py
In #169 we created a Mathematica builder (`gslab_scons/builders/build_mathematica.py`) and a unit test for it (`gslab_scons/tests/test_build_mathematica.py`). We also made some changes to other scripts so that both the builder and the test work. For the unit test, I adopted the style of `gslab_scons/tests/test_build_r.py` with minimal changes.
@zkashner, per [here](https://github.com/gslab-econ/gslab_python/issues/169#issuecomment-764705829) I've assigned you as the reviewer but please feel free to hand it over to someone else.
> Pull Request for #169: Create Mathematica builder

- gslab_misc/SaveData/SaveData.py
- gslab_misc/SaveData/__init__.py
- gslab_misc/SaveData/tests/__init__.py
- gslab_misc/SaveData/tests/test_main.py
- gslab_misc/__init__.py
- manifest.log
In this issue I added a Python version of SaveData together with unit tests.
> Pull Request for #172: SaveData for Python
